# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'frontendcoffeemobile' do
  # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


  # Pods for nexus
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'DevSupport'
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link - FROM REACT NATIVE DOCS
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'frontendcoffeemobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
