export const WELCOME_SCREEN = "WELCOME_SCREEN"
export const MAP_SCREEN = "MAP_SCREEN"
export const SET_PARAMETERS_SCREEN = "SET_PARAMETERS_SCREEN"
export const LOADING_SCREEN = "LOADING_SCREEN"
export const MODEL_RESULTS_SCREEN = "MODEL_RESULTS_SCREEN"
export const SHADE_OPTIMIZED_SCREEN = "SHADE_OPTIMIZED_SCREEN"
export const SETTINGS_SCREEN = "SETTINGS_SCREEN"
export const DRAWER_CONTAINER = "DRAWER_CONTAINER"
export const POINT_SCREEN = "POINT_SCREEN"

export const CALCULATE_YIELD = "CALCULATE_YIELD"
export const OPTIMIZE_SHADE = "OPTIMIZE_SHADE"

export const SAVE_DATA_LOCALLY = "SAVE_DATA_LOCALLY"

export const YIELD = `YIELD`
export const OPTIMIZE = `OPTIMIZE`
